<a href="https://colab.research.google.com/github/rraasch/pytorch_training/blob/main/multiple_lr_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

This example is for a multiple regression that has a 2D input vector.

In [3]:
import torch
from torch.nn import Linear

In [4]:
torch.manual_seed(1)

In [5]:
model = Linear(in_features = 2, out_features = 1)

In [6]:
list(model.parameters())

[Parameter containing:
 tensor([[ 0.3643, -0.3121]], requires_grad=True),
 Parameter containing:
 tensor([-0.1371], requires_grad=True)]

In [8]:
X = torch.tensor([1.0,3.0])
yhat = model(X)
print(yhat)

tensor([-0.7090], grad_fn=<AddBackward0>)


In [11]:
X = torch.tensor([[1.0, 1.0], [2.0, 2.0], [1.0, 3.0]])
yhat = model(X)
print(yhat)

tensor([[-0.0848],
        [-0.0326],
        [-0.7090]], grad_fn=<AddmmBackward0>)


If we wanted to make a custom module for MLR:

In [12]:
import torch.nn as nn

In [19]:
class MLR(nn.Module):
    def __init__(self, input_size, output_size):
        super(MLR, self).__init__()
        self.linear = nn.Linear(input_size, output_size)

    def forward(self, X):
        out = self.linear(X)
        return out

In [20]:
torch.manual_seed(1)

In [21]:
model = MLR(2,1)

In [22]:
X = torch.tensor([1.0, 2.0])
yhat = model(X)
print(yhat)

tensor([-0.3969], grad_fn=<AddBackward0>)


Now for multiple output linear regression:

In [23]:
model = nn.Linear(2, 2)

In [24]:
X = torch.tensor([1.0, 2.0])
yhat = model(X)
print(yhat)

tensor([-0.6398,  0.2314], grad_fn=<AddBackward0>)


In [25]:
X = torch.tensor([[1.0, 2.0],[1.0, 3.0],[4.0, 4.0]])
yhat = model(X)
print(yhat)

tensor([[-0.6398,  0.2314],
        [-1.3055,  0.0860],
        [-0.9755,  1.2127]], grad_fn=<AddmmBackward0>)


TRAINING A MLR MODEL

In [26]:
import torch.nn as nn

class LR(nn.Module):
    def __init__(self, input_size, output_size):
        super(LR, self).__init__()
        self.linear = nn.Linear(input_size, output_size)

    def forward(self, x):
        out = self.linear(x)
        return out

In [27]:
from torch.utils.data import Dataset, DataLoader

In [53]:
torch.tensor([[1.0, -1.0], [1.0, -1.0]])

tensor([[ 1., -1.],
        [ 1., -1.]])

In [56]:
class data2D(Dataset):
    def __init__(self):
        self.x = torch.zeros(20,2)
        self.x[:,0] = torch.arange(-1.0, 1.0, 0.1)
        self.x[:,1] = torch.arange(-1.0, 1.0, 0.1)
        self.w = torch.tensor([[1.0, -1.0], [1.0, -1.0]])
        self.b = torch.tensor([[1.0, -1.0]])
        self.f = torch.mm(self.x, self.w)+self.b
        self.y = self.f+0.1*torch.randn((self.x.shape[0], 1))
        self.len = self.x.shape[0]

    def __getitem__(self, index):
        return self.x[index], self.y[index]

    def __len__(self):
        return self.len

In [57]:
data_set = data2D()

In [58]:
criterion = nn.MSELoss()
trainloader = DataLoader(dataset = data_set, batch_size = 1)

In [59]:
model = LR(2, 2)
optimizer = torch.optim.SGD(model.parameters(), lr = 0.1)

In [61]:
for epoch in range(200):
    for x,y in trainloader:
        yhat = model(x)
        loss = criterion(yhat, y)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
    print(loss.item())


0.7362796068191528
0.039826732128858566
0.006636898498982191
0.004760971292853355
0.00458197295665741
0.004554556682705879
0.004549575038254261
0.00454865675419569
0.0045484635047614574
0.004548431374132633
0.004548447672277689
0.004548431374132633
0.004548431374132633
0.004548431374132633
0.004548431374132633
0.004548431374132633
0.004548431374132633
0.004548431374132633
0.004548431374132633
0.004548431374132633
0.004548431374132633
0.004548431374132633
0.004548431374132633
0.004548431374132633
0.004548431374132633
0.004548431374132633
0.004548431374132633
0.004548431374132633
0.004548431374132633
0.004548431374132633
0.004548431374132633
0.004548431374132633
0.004548431374132633
0.004548431374132633
0.004548431374132633
0.004548431374132633
0.004548431374132633
0.004548431374132633
0.004548431374132633
0.004548431374132633
0.004548431374132633
0.004548431374132633
0.004548431374132633
0.004548431374132633
0.004548431374132633
0.004548431374132633
0.004548431374132633
0.00454843137413

In [62]:
list(model.parameters())

[Parameter containing:
 tensor([[ 0.6742,  1.3950],
         [-1.4035, -0.5273]], requires_grad=True),
 Parameter containing:
 tensor([ 1.0122, -0.9878], requires_grad=True)]