<a href="https://colab.research.google.com/github/rraasch/pytorch_training/blob/main/torch_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install torch

In [ ]:
import torch

In [ ]:
from torch.utils.data import Dataset

In [ ]:
class toy_set(Dataset):
    def __init__(self, length = 100, transform = None):
        self.x = 2*torch.ones(length,2)
        self.y = torch.ones(length, 1)
        self.len = length
        self.transform = transform

    def __getitem__(self, index):
        sample = self.x[index], self.y[index]
        if self.transform:
            sample = self.transform(sample)
        return sample

    def __len__(self):
        return self.len

In [ ]:
dataset = toy_set()

In [ ]:
len(dataset)

100

In [ ]:
dataset[0]

(tensor([2., 2.]), tensor([1.]))

In [ ]:
#create transform class
class add_mult(object):
    def __init__(self, addx=1, muly=1):
        self.addx = addx
        self.muly = muly

    def __call__(self, sample):
        x = sample[0]
        y = sample[1]
        x = x+self.addx
        y = y*self.muly
        sample = x, y
        return sample

In [ ]:
#use the transorm
a_m = add_mult(2, 3)

dataset_ = toy_set(transform = a_m)

In [ ]:
dataset_[0]

(tensor([4., 4.]), tensor([3.]))

In [ ]:
#create another transorm
class mult(object):
    def __init__(self, mul=100):
        self.mul = mul

    def __call__(self, sample):
        x=sample[0]
        y=sample[1]
        x = x*self.mul
        y = y*self.mul
        sample = x, y
        return sample

In [ ]:
from torchvision import transforms

In [ ]:
data_transform = transforms.Compose([add_mult(), mult()])

In [ ]:
x_, y_ = data_transform(dataset[0])

In [ ]:
print(x_, y_)

tensor([500., 500.]) tensor([300.])


In [ ]:
#create new dataset with the two transforms
dataset_ = toy_set(length = 200, transform = data_transform)

In [ ]:
dataset_[0]

(tensor([300., 300.]), tensor([100.]))